server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codecube?useSSL=true&useUnicode=true&characterEncoding=gbk&serverTimezone=UTC
    username: root
    password: 1314920xuewei